-- 1. CREATE ENUM
DO $$ BEGIN
    CREATE TYPE "DeviceStatus" AS ENUM ('ONLINE', 'OFFLINE', 'WARNING');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. CREATE DEVICE TABLE
CREATE TABLE IF NOT EXISTS "Device" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "deviceId" TEXT NOT NULL,
    "macAddress" TEXT,
    "zoneId" TEXT NOT NULL,
    "firmware" TEXT,
    "ipAddress" TEXT,
    "status" "DeviceStatus" NOT NULL DEFAULT 'ONLINE',
    "lastSeen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Device_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Device_zoneId_fkey" FOREIGN KEY ("zoneId") REFERENCES "Zone"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "Device_deviceId_key" ON "Device"("deviceId");

-- 3. ALTER SENSOR TABLE
ALTER TABLE "Sensor" ADD COLUMN IF NOT EXISTS "esp32Id" TEXT;
ALTER TABLE "Sensor" ADD COLUMN IF NOT EXISTS "gpioPin" TEXT;

DO $$ BEGIN
    ALTER TABLE "Sensor" ADD CONSTRAINT "Sensor_esp32Id_fkey" FOREIGN KEY ("esp32Id") REFERENCES "Device"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 4. ALTER FAN TABLE
ALTER TABLE "Fan" ADD COLUMN IF NOT EXISTS "esp32Id" TEXT;
ALTER TABLE "Fan" ADD COLUMN IF NOT EXISTS "relayChannel" INTEGER;
ALTER TABLE "Fan" ADD COLUMN IF NOT EXISTS "gpioPin" TEXT;

DO $$ BEGIN
    ALTER TABLE "Fan" ADD CONSTRAINT "Fan_esp32Id_fkey" FOREIGN KEY ("esp32Id") REFERENCES "Device"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 5. ALTER COOLER TABLE
ALTER TABLE "Cooler" ADD COLUMN IF NOT EXISTS "esp32Id" TEXT;
ALTER TABLE "Cooler" ADD COLUMN IF NOT EXISTS "relayChannel" INTEGER;
ALTER TABLE "Cooler" ADD COLUMN IF NOT EXISTS "gpioPin" TEXT;

DO $$ BEGIN
    ALTER TABLE "Cooler" ADD CONSTRAINT "Cooler_esp32Id_fkey" FOREIGN KEY ("esp32Id") REFERENCES "Device"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 6. DISABLE RLS ON DEVICE (For straightforward local dev testing)
ALTER TABLE "Device" DISABLE ROW LEVEL SECURITY;
